# Generated by Django 4.2 on 2025-04-06 05:47

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('description', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255))),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
